export * from 'katsu-curry'
export * from './array'
export * from './choice'
export * from './filter'
export * from './flip'
export * from './future'
export * from './iterate'
export * from './map'
export * from './math'
import {random as _random} from './random'
import * as f from './random-floor'
import * as t from './random-take'
import * as w from './random-word'
import * as s from './random-shuffle'
export * from './reduce'
export * from './reject'
export * from './string'
export * from './ternary'
export * from './triplet'
export * from './types'
export * from './which'

export const random = Object.assign(_random, f, t, w, s)
